# This is a basic workflow to help you get started with Actions

name: update-branch

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-hackathon:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/github-script@0.9.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let repo = { owner: 'agoric-labs', repo: 'wsl-ci-test' };
          let f = await github.git.getRef({ref: 'heads/master', ...repo});
          let sha = f.data.object.sha;
          await github.git.updateRef({ref:  'heads/hackathon', sha, ...repo});
